<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>DeepSigma.AI.FluentPromptBuilder.Sample</RootNamespace>
    <AssemblyName>DeepSigma.AI.FluentPromptBuilder.Sample</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DeepSigma.AI.FluentPromptBuilder\DeepSigma.AI.FluentPromptBuilder.csproj" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <None Update="prompts\**\*.prompt.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
